version: "3.9"

services:
  db:
    image: postgres:15
    container_name: njord_db
    restart: always
    environment:
      POSTGRES_DB: njord
      POSTGRES_USER: njord
      POSTGRES_PASSWORD: njordpass
    volumes:
      - njord_db_data:/var/lib/postgresql/data

  collector:
    build: .
    container_name: njord_collector
    command: python collector.py
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: njord
      DB_USER: njord
      DB_PASSWORD: njordpass
      API_KEY_ID: 3150711e-c446-41f1-a58a-87abfa2b21a7
      API_KEY_SECRET: 8sx66o88w320cm6ubrb95smeubjhwq0s
      ORG_ID: 4266987b-aeaa-4794-8cf6-ba6c54b898de

  api:
    build: .
    container_name: njord_api
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    restart: always
    depends_on:
      - db
    ports:
      - "8040:8000"
    environment:
      DB_HOST: db
      DB_NAME: njord
      DB_USER: njord
      DB_PASSWORD: njordpass
      API_KEY_ID: 3150711e-c446-41f1-a58a-87abfa2b21a7
      API_KEY_SECRET: 8sx66o88w320cm6ubrb95smeubjhwq0s
      ORG_ID: 4266987b-aeaa-4794-8cf6-ba6c54b898de


volumes:
  njord_db_data: