version: "3.9"

services:
  db:
    image: postgres:15
    container_name: njord_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: njord
      POSTGRES_USER: njord
      POSTGRES_PASSWORD: njordpass
    volumes:
      - njord_db_data:/var/lib/postgresql/data

  collector:
    build: .
    volumes:
      - .:/app
    container_name: njord_collector
    command: python collector.py
    restart: unless-stopped
    depends_on:
      - db


  api:
    build: .
    volumes:
      - .:/app
    container_name: njord_api
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8040:8000"



volumes:
  njord_db_data: